name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: nix fmt check
        run: nix run nixpkgs#nixpkgs-fmt -- --check flake.nix
      - name: statix
        run: nix run nixpkgs#statix -- check .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: build
        run: nix build -L
